export enum EventTypes{
    NEW_INBOUND_CALL="NEW_INBOUND_CALL",
    ACTION_SUCCESSFUL="ACTION_SUCCESSFUL",
    CALL_ANSWERED="CALL_ANSWERED",
    ACTION_FAILED="ACTION_FAILED",
    INVALID_LAMBDA_RESPONSE="INVALID_LAMBDA_RESPONSE",
    HANGUP="HANGUP"
}